#!/usr/bin/env python3
"""Build a restartable Slurm bundle for the 302-sample global Japanese-origin tree.

Input is the source-safe 302-row panel generated by
``build_japan_origin_global_public_panel.py``.  The bundle uses safe synthetic
tip IDs so commas/spaces/synonyms in source metadata cannot break shell parsing,
while preserving an explicit tip map.

Primary mapping is BWA in HybPiper 2.3.4; BLASTx is a predeclared mapping
sensitivity.  Primary tree admission is the frozen conservative-241 universe
intersected with current occupancy >=0.80 and zero current paralog warnings.
If <100 loci survive, execution stops rather than relaxing filters post hoc.
"""
from __future__ import annotations
import argparse,csv,json,shlex
from pathlib import Path

REF_SHA='77d510ef101d08a7a23a4df391d077d3b7f75482c66f7f4bea6d32cf290ced2c'
EXPECTED_SAMPLES=302
EXPECTED_RUNS=303

def clean(x):return str(x or '').strip()
def read_panel(path):
    with path.open(encoding='utf-8-sig',newline='') as h:rows=[{k:clean(v) for k,v in r.items()} for r in csv.DictReader(h)]
    req={'panel_id','source_study','assay','analysis_taxon_label','voucher','biosample','run_accessions','run_count'}
    if not rows or not req<=set(rows[0]):raise ValueError(f'global panel requires columns {sorted(req)}')
    if len(rows)!=EXPECTED_SAMPLES:raise ValueError(f'expected {EXPECTED_SAMPLES} rows, found {len(rows)}')
    if len({r['panel_id'] for r in rows})!=EXPECTED_SAMPLES:raise ValueError('panel_id values are not unique')
    if sum(int(r['run_count']) for r in rows)!=EXPECTED_RUNS:raise ValueError('public run-count drift')
    for r in rows:
        runs=[x for x in r['run_accessions'].split('|') if x]
        if len(runs)!=int(r['run_count']) or any(not x.startswith('SRR') for x in runs):raise ValueError(f'invalid run list for {r["panel_id"]}')
    return rows
def write(path,text,mode=0o644):path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8');path.chmod(mode)
def sample_tsv(path,rows):
    fields=['index','tip_id','panel_id','source_study','assay','analysis_taxon_label','voucher','biosample','run_accessions','run_count']
    with path.open('w',encoding='utf-8',newline='') as h:
        w=csv.DictWriter(h,fieldnames=fields,delimiter='\t',lineterminator='\n');w.writeheader()
        for i,r in enumerate(rows):
            w.writerow({'index':i,'tip_id':f'JOG{i+1:04d}','panel_id':r['panel_id'],'source_study':r['source_study'],'assay':r['assay'],'analysis_taxon_label':r['analysis_taxon_label'],'voucher':r['voucher'],'biosample':r['biosample'],'run_accessions':r['run_accessions'],'run_count':r['run_count']})
def env_yml():return '''name: eazami-japan-origin-global
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - hybpiper=2.3.4
  - sra-tools
  - fastp
  - pigz
  - bwa
  - samtools
  - blast
  - spades
  - exonerate
  - mafft
  - iqtree
  - biopython
'''
def common():return '''set -euo pipefail
BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$BUNDLE_DIR/../.." && pwd)}"
RESULT_ROOT="${RESULT_ROOT:-$PWD/results/japan_origin_global}"
ENV_PREFIX="${ENV_PREFIX:-$REPO_ROOT/.conda/eazami-japan-origin-global}"
export BUNDLE_DIR REPO_ROOT RESULT_ROOT ENV_PREFIX
if command -v micromamba >/dev/null 2>&1; then
  if [[ ! -x "$ENV_PREFIX/bin/python" ]]; then micromamba create -y -p "$ENV_PREFIX" -f "$BUNDLE_DIR/env.yml"; fi
  RUN=(micromamba run -p "$ENV_PREFIX")
elif command -v mamba >/dev/null 2>&1; then
  if [[ ! -x "$ENV_PREFIX/bin/python" ]]; then mamba env create -y -p "$ENV_PREFIX" -f "$BUNDLE_DIR/env.yml"; fi
  RUN=(mamba run -p "$ENV_PREFIX")
else echo "micromamba or mamba required" >&2; exit 2; fi
mkdir -p "$RESULT_ROOT"
'''
def row_shell():return '''eval "$(python - "$BUNDLE_DIR/sample_manifest.tsv" "$IDX" <<'PY'
import csv,shlex,sys
p,idx=sys.argv[1],int(sys.argv[2])
with open(p,encoding='utf-8',newline='') as h:rows=list(csv.DictReader(h,delimiter='\t'))
r=rows[idx]
for k in ('tip_id','run_accessions','run_count','source_study','assay'):
 print(f'{k.upper()}={shlex.quote(r[k])}')
PY
)"
'''
def prep():return '#!/usr/bin/env bash\n'+common()+'''mkdir -p "$RESULT_ROOT/inputs/reference" "$RESULT_ROOT/inputs/locus_sets"
"${RUN[@]}" python "$REPO_ROOT/analysis/recover_comp1061_original_hybpiper_reference.py" --outdir "$RESULT_ROOT/inputs/reference"
python - <<'PY'
import json,os,pathlib
root=pathlib.Path(os.environ['RESULT_ROOT']);c=json.loads((root/'inputs/reference/comp1061_original_reference_contract.json').read_text())
assert c['sha256']==''' + repr(REF_SHA) + ''' and c['locus_count']==1061
PY
"${RUN[@]}" python "$REPO_ROOT/analysis/recover_moreyra_author_repository.py" --outdir "$RESULT_ROOT/inputs/moreyra_author_repo" --force
"${RUN[@]}" python "$REPO_ROOT/analysis/summarize_moreyra_locus_filter.py" --audit-dir "$RESULT_ROOT/inputs/moreyra_author_repo"
"${RUN[@]}" python "$REPO_ROOT/analysis/export_moreyra_locus_manifests.py" --input "$RESULT_ROOT/inputs/moreyra_author_repo/paralog_locus_filter_reconstruction.csv" --outdir "$RESULT_ROOT/inputs/locus_sets"
for x in moreyra_public_1061_loci.txt moreyra_reproducible_531_candidate_loci.txt moreyra_conservative_241_no_warning_loci.txt; do test -s "$RESULT_ROOT/inputs/locus_sets/$x"; done
echo global_inputs_checkpoint=complete
'''
def fetch():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-fetch
#SBATCH --array=0-301%20
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH --time=24:00:00
#SBATCH --output=jog_fetch_%A_%a.out
#SBATCH --error=jog_fetch_%A_%a.err
'''+common()+'''IDX="${SLURM_ARRAY_TASK_ID:?}"
'''+row_shell()+'''OUT="$RESULT_ROOT/reads/$TIP_ID"; mkdir -p "$OUT/sra" "$OUT/raw" "$OUT/combined" "$OUT/trimmed" "$OUT/scratch"
if [[ -s "$OUT/trimmed/$TIP_ID.R1.trim.fastq.gz" && -s "$OUT/trimmed/$TIP_ID.R2.trim.fastq.gz" ]]; then echo already_complete; exit 0; fi
IFS='|' read -r -a ACCS <<< "$RUN_ACCESSIONS"
if [[ "${#ACCS[@]}" -ne "$RUN_COUNT" ]]; then echo "run-count mismatch $TIP_ID" >&2; exit 3; fi
R1S=(); R2S=()
for ACC in "${ACCS[@]}"; do
  "${RUN[@]}" prefetch "$ACC" --output-directory "$OUT/sra"
  SRA=$(find "$OUT/sra" -name "$ACC.sra" -print -quit); test -s "$SRA"
  "${RUN[@]}" vdb-validate "$SRA"
  if [[ ! -s "$OUT/raw/${ACC}_1.fastq.gz" || ! -s "$OUT/raw/${ACC}_2.fastq.gz" ]]; then
    "${RUN[@]}" fasterq-dump "$SRA" --split-files --threads 8 --temp "$OUT/scratch" --outdir "$OUT/raw"
    test -s "$OUT/raw/${ACC}_1.fastq"; test -s "$OUT/raw/${ACC}_2.fastq"
    "${RUN[@]}" pigz -p 8 "$OUT/raw/${ACC}_1.fastq" "$OUT/raw/${ACC}_2.fastq"
  fi
  R1S+=("$OUT/raw/${ACC}_1.fastq.gz"); R2S+=("$OUT/raw/${ACC}_2.fastq.gz")
done
cat "${R1S[@]}" > "$OUT/combined/$TIP_ID.R1.fastq.gz"; cat "${R2S[@]}" > "$OUT/combined/$TIP_ID.R2.fastq.gz"
test -s "$OUT/combined/$TIP_ID.R1.fastq.gz"; test -s "$OUT/combined/$TIP_ID.R2.fastq.gz"
"${RUN[@]}" fastp -i "$OUT/combined/$TIP_ID.R1.fastq.gz" -I "$OUT/combined/$TIP_ID.R2.fastq.gz" -o "$OUT/trimmed/$TIP_ID.R1.trim.fastq.gz" -O "$OUT/trimmed/$TIP_ID.R2.trim.fastq.gz" --thread 8 --json "$OUT/trimmed/$TIP_ID.fastp.json" --html "$OUT/trimmed/$TIP_ID.fastp.html"
test -s "$OUT/trimmed/$TIP_ID.R1.trim.fastq.gz"; test -s "$OUT/trimmed/$TIP_ID.R2.trim.fastq.gz"; touch "$OUT/trimmed/.complete"
'''
def hyb(mode):
    bwa=' --bwa' if mode=='bwa' else ''
    return f'''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-{mode}
#SBATCH --array=0-301%16
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=48:00:00
#SBATCH --output=jog_{mode}_%A_%a.out
#SBATCH --error=jog_{mode}_%A_%a.err
'''+common()+'''IDX="${SLURM_ARRAY_TASK_ID:?}"
'''+row_shell()+f'''R1="$RESULT_ROOT/reads/$TIP_ID/trimmed/$TIP_ID.R1.trim.fastq.gz"; R2="$RESULT_ROOT/reads/$TIP_ID/trimmed/$TIP_ID.R2.trim.fastq.gz"; TARGET="$RESULT_ROOT/inputs/reference/comp1061_hybpiper_reference.fasta"; OUT="$RESULT_ROOT/hybpiper_{mode}"
test -s "$R1"; test -s "$R2"; test -s "$TARGET"; mkdir -p "$OUT"; [[ -s "$OUT/$TIP_ID.tar.gz" ]] && exit 0
cd "$OUT"; "${{RUN[@]}}" hybpiper assemble -t_dna "$TARGET" -r "$R1" "$R2" --prefix "$TIP_ID" --cpu 16{bwa} --no_intronerate --compress_sample_folder; cd - >/dev/null; test -s "$OUT/$TIP_ID.tar.gz"
'''
def qc():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-qc
#SBATCH --cpus-per-task=32
#SBATCH --mem=96G
#SBATCH --time=24:00:00
'''+common()+'''MODE="${MODE:-bwa}"; [[ "$MODE" == bwa || "$MODE" == blastx ]]; HYB="$RESULT_ROOT/hybpiper_$MODE"; TARGET="$RESULT_ROOT/inputs/reference/comp1061_hybpiper_reference.fasta"; QC="$RESULT_ROOT/qc_$MODE"; mkdir -p "$QC"
cut -f2 "$BUNDLE_DIR/sample_manifest.tsv" | tail -n +2 > "$QC/sample_names.txt"
cd "$QC"
"${RUN[@]}" hybpiper stats -t_dna "$TARGET" gene "$QC/sample_names.txt" --hybpiper_dir "$HYB" --cpu 32 --no_heatmap --seq_lengths_filename seq_lengths --stats_filename hybpiper_stats
"${RUN[@]}" hybpiper retrieve_sequences dna -t_dna "$TARGET" --sample_names "$QC/sample_names.txt" --hybpiper_dir "$HYB" --fasta_dir "$QC/retrieved_dna" --cpu 32
"${RUN[@]}" hybpiper paralog_retriever "$QC/sample_names.txt" -t_dna "$TARGET" --hybpiper_dir "$HYB" --fasta_dir_all "$QC/paralogs_all" --paralog_report_filename "$QC/paralog_report" --paralogs_above_threshold_report_filename "$QC/paralog_loci_any" --paralogs_list_threshold_percentage 0 --no_heatmap --cpu 32
cd - >/dev/null; test -s "$QC/hybpiper_stats.tsv"; test -d "$QC/retrieved_dna"; test -s "$QC/paralog_report"
'''
def treeprep():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-treeprep
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=08:00:00
'''+common()+'''MODE="${MODE:-bwa}"; QC="$RESULT_ROOT/qc_$MODE"; TREE="$RESULT_ROOT/tree_$MODE"; mkdir -p "$TREE/current_qc" "$TREE/inputs"
"${RUN[@]}" python "$REPO_ROOT/analysis/summarize_japan_origin_global_comp1061_qc.py" --manifest "$BUNDLE_DIR/sample_manifest.csv" --retrieved-dir "$QC/retrieved_dna" --paralog-report "$QC/paralog_report" --locus-dir "$RESULT_ROOT/inputs/locus_sets" --outdir "$TREE/current_qc"
CURRENT="$TREE/current_qc/current_strict_conservative_241_loci.txt"; test -s "$CURRENT"
"${RUN[@]}" python "$REPO_ROOT/analysis/prepare_japan_origin_global_comp1061_tree_inputs.py" --manifest "$BUNDLE_DIR/sample_manifest.csv" --locus-list "$CURRENT" --retrieved-dir "$QC/retrieved_dna" --target "$RESULT_ROOT/inputs/reference/comp1061_hybpiper_reference.fasta" --outdir "$TREE/inputs"
'''
def align():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-align
#SBATCH --array=0-240%24
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=04:00:00
'''+common()+'''MODE="${MODE:-bwa}"; TREE="$RESULT_ROOT/tree_$MODE"; IDX="${SLURM_ARRAY_TASK_ID:?}"; LOCUS=$(sed -n "$((IDX+1))p" "$TREE/inputs/eligible_loci.txt" || true); [[ -n "$LOCUS" ]] || exit 0; IN="$TREE/inputs/loci_unaligned/$LOCUS.fasta"; OUT="$TREE/alignments/$LOCUS.aln.fasta"; mkdir -p "$TREE/alignments"; [[ -s "$OUT" ]] && exit 0; test -s "$IN"; "${RUN[@]}" mafft --auto --thread 4 "$IN" > "$OUT"; test -s "$OUT"
'''
def gene():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-genetree
#SBATCH --array=0-240%20
#SBATCH --cpus-per-task=4
#SBATCH --mem=12G
#SBATCH --time=08:00:00
'''+common()+'''MODE="${MODE:-bwa}"; TREE="$RESULT_ROOT/tree_$MODE"; IDX="${SLURM_ARRAY_TASK_ID:?}"; LOCUS=$(sed -n "$((IDX+1))p" "$TREE/inputs/eligible_loci.txt" || true); [[ -n "$LOCUS" ]] || exit 0; ALN="$TREE/alignments/$LOCUS.aln.fasta"; PREFIX="$TREE/gene_trees/$LOCUS"; mkdir -p "$TREE/gene_trees"; [[ -s "$PREFIX.treefile" ]] && exit 0; test -s "$ALN"; "${RUN[@]}" iqtree2 -s "$ALN" -m MFP -B 1000 --alrt 1000 -T 4 -o OUTGROUP_lett,OUTGROUP_sunf --prefix "$PREFIX"; test -s "$PREFIX.treefile"
'''
def concat():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-concat
#SBATCH --cpus-per-task=32
#SBATCH --mem=128G
#SBATCH --time=48:00:00
'''+common()+'''MODE="${MODE:-bwa}"; TREE="$RESULT_ROOT/tree_$MODE"; mkdir -p "$TREE/concat"
"${RUN[@]}" python "$REPO_ROOT/analysis/concatenate_colour_rate_comp1061_alignments.py" --eligible-loci "$TREE/inputs/eligible_loci.txt" --alignment-dir "$TREE/alignments" --primary-runs "$BUNDLE_DIR/sample_manifest.csv" --output "$TREE/concat/concat.fasta" --partitions "$TREE/concat/partitions.csv" --summary "$TREE/concat/concat_summary.json"
"${RUN[@]}" iqtree2 -s "$TREE/concat/concat.fasta" -m MFP -B 1000 --alrt 1000 -T AUTO -o OUTGROUP_lett,OUTGROUP_sunf --prefix "$TREE/concat/japan_origin_global_concat"; test -s "$TREE/concat/japan_origin_global_concat.treefile"
'''
def accept():return '''#!/usr/bin/env bash
#SBATCH --job-name=EAzami-jog-accept
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --time=02:00:00
'''+common()+'''MODE="${MODE:-bwa}"; TREE="$RESULT_ROOT/tree_$MODE"; TREEFILE="$TREE/concat/japan_origin_global_concat.treefile"; test -s "$TREEFILE"
python - "$TREEFILE" "$TREE/concat/concat_summary.json" "$TREE/tree_provenance.json" <<'PY'
import hashlib,json,pathlib,sys
tr=pathlib.Path(sys.argv[1]); cs=json.loads(pathlib.Path(sys.argv[2]).read_text()); out=pathlib.Path(sys.argv[3])
prov={'tree_sha256':hashlib.sha256(tr.read_bytes()).hexdigest(),'analysis_name':'EAzami 302-sample global public Cirsium origin compatibility tree','branch_length_interpretation':'IQ-TREE maximum-likelihood substitutions per site on concatenated Compositae1061-compatible coding-sequence alignment','rooting_definition':'OUTGROUP_lett and OUTGROUP_sunf define the root; OUTGROUP_saff is retained as an optional near Cardueae reference','required_outgroup_tips':['OUTGROUP_lett','OUTGROUP_sunf'],'required_reference_tips':cs['reference_tips'],'support_metric_definition':'IQ-TREE ultrafast bootstrap 1000 plus SH-aLRT 1000; per-locus gene trees retained for coalescent/topology sensitivity','source_or_pipeline_provenance':'302 public biological samples / 303 runs from Moreyra 2025 plus Chang 2025/2026; original Compositae1061 reference; strict frozen-241 current occupancy >=0.80 and zero-current-paralog admission; HybPiper 2.3.4; MAFFT; IQ-TREE','topology_uncertainty_status':'bootstrap_or_gene_tree_sensitivity'}
out.write_text(json.dumps(prov,indent=2)+'\n')
PY
"${RUN[@]}" python "$REPO_ROOT/analysis/validate_japan_origin_global_tree.py" --tree "$TREEFILE" --manifest "$BUNDLE_DIR/sample_manifest.csv" --provenance "$TREE/tree_provenance.json" --output "$TREE/tree_acceptance.json"
'''
def submit_data(mode):
    h='02_hybpiper_bwa_slurm.sh' if mode=='bwa' else '02b_hybpiper_blastx_slurm.sh'
    return f'''#!/usr/bin/env bash
set -euo pipefail
prep=$(sbatch --parsable 00_prepare_inputs_slurm.sh); fetch=$(sbatch --parsable --dependency=afterok:$prep 01_fetch_trim_slurm.sh); hyb=$(sbatch --parsable --dependency=afterok:$fetch {h}); qc=$(sbatch --parsable --dependency=afterok:$hyb --export=ALL,MODE={mode} 03_retrieve_qc_slurm.sh); printf 'prepare=%s\nfetch=%s\nhybpiper=%s\nqc=%s\n' "$prep" "$fetch" "$hyb" "$qc"
'''
def submit_tree():return '''#!/usr/bin/env bash
set -euo pipefail
MODE="${MODE:-bwa}"; prep=$(sbatch --parsable --export=ALL,MODE="$MODE" 04_prepare_tree_inputs_slurm.sh); aln=$(sbatch --parsable --dependency=afterok:$prep --export=ALL,MODE="$MODE" 05_align_loci_slurm.sh); gene=$(sbatch --parsable --dependency=afterok:$aln --export=ALL,MODE="$MODE" 06_gene_trees_slurm.sh); con=$(sbatch --parsable --dependency=afterok:$aln --export=ALL,MODE="$MODE" 07_concat_tree_slurm.sh); acc=$(sbatch --parsable --dependency=afterok:$gene:$con --export=ALL,MODE="$MODE" 08_accept_tree_slurm.sh); printf 'prep=%s\nalign=%s\ngene=%s\nconcat=%s\naccept=%s\n' "$prep" "$aln" "$gene" "$con" "$acc"
'''
def main():
    p=argparse.ArgumentParser();p.add_argument('--panel',type=Path,required=True);p.add_argument('--outdir',type=Path,required=True);a=p.parse_args();rows=read_panel(a.panel);a.outdir.mkdir(parents=True,exist_ok=True);sample_tsv(a.outdir/'sample_manifest.tsv',rows)
    # CSV copy with safe tree IDs plus metadata; generic tree/QC scripts consume this.
    tsv=list(csv.DictReader((a.outdir/'sample_manifest.tsv').open(encoding='utf-8'),delimiter='\t'))
    with (a.outdir/'sample_manifest.csv').open('w',encoding='utf-8',newline='') as h:
        w=csv.DictWriter(h,fieldnames=list(tsv[0]));w.writeheader();w.writerows(tsv)
    write(a.outdir/'env.yml',env_yml())
    scripts={'00_prepare_inputs_slurm.sh':prep(),'01_fetch_trim_slurm.sh':fetch(),'02_hybpiper_bwa_slurm.sh':hyb('bwa'),'02b_hybpiper_blastx_slurm.sh':hyb('blastx'),'03_retrieve_qc_slurm.sh':qc(),'04_prepare_tree_inputs_slurm.sh':treeprep(),'05_align_loci_slurm.sh':align(),'06_gene_trees_slurm.sh':gene(),'07_concat_tree_slurm.sh':concat(),'08_accept_tree_slurm.sh':accept(),'submit_bwa_chain.sh':submit_data('bwa'),'submit_blastx_chain.sh':submit_data('blastx'),'submit_tree_chain.sh':submit_tree()}
    for n,t in scripts.items():write(a.outdir/n,t,0o755)
    m={'bundle_version':'japan_origin_global_hpc_bundle_v1','biological_samples':302,'public_runs':303,'safe_tip_ids':True,'primary_mapping':'bwa','mapping_sensitivity':'blastx','hybpiper_version':'2.3.4','frozen_primary_locus_universe':241,'primary_current_occupancy_gate':0.80,'current_paralog_gate':'zero HybPiper >1-copy warnings across all 302 samples','minimum_primary_loci_to_launch':100,'automatic_filter_relaxation_allowed':False,'tree_products':['per-locus IQ-TREE gene trees','concatenated IQ-TREE ML tree'],'coalescent_stage_input':'per-locus gene-tree directory retained for ASTRAL/coalescent sensitivity','tree_completed':False,'japanese_origin_inference_completed':False,'new_china_sampling_freeze_allowed':False}
    write(a.outdir/'execution_manifest.json',json.dumps(m,indent=2)+'\n');print(json.dumps(m,indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
