#!/usr/bin/env python3
"""Screen licensed Japan-local Cirsium pendulum images with the pinned Azami colour algorithm.

This wrapper intentionally does not download images and does not vendor the Azami
measurement implementation. A workflow checks out the pinned Azami commit,
downloads only registry rows explicitly marked for automated use, and points this
script at the existing ``colour_measurement`` function.

The output is a calibration screen, not a population phenotype. The public images
were not generated by the original detector/crop pipeline, and multiple images from
one locality/date are not independent population replicates.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
import math
import statistics
from pathlib import Path

import cv2


def read_csv(path: Path):
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def load_azami_measurement(path: Path):
    spec = importlib.util.spec_from_file_location("azami_primary_measurement", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not import Azami measurement module: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if not hasattr(module, "colour_measurement"):
        raise RuntimeError("pinned Azami module has no colour_measurement function")
    return module


def sha256(path: Path):
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def median_abs_deviation(values):
    if not values:
        return None
    med = statistics.median(values)
    return statistics.median(abs(x - med) for x in values)


def truthy(value):
    return str(value or "").strip().lower() in {"1", "true", "yes", "y"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--registry", type=Path, required=True)
    parser.add_argument("--image-dir", type=Path, required=True)
    parser.add_argument("--azami-measure-script", type=Path, required=True)
    parser.add_argument("--colour-confidence-floor", type=float, default=0.55)
    parser.add_argument("--per-image-output", type=Path, required=True)
    parser.add_argument("--summary-output", type=Path, required=True)
    args = parser.parse_args()

    rows = [row for row in read_csv(args.registry) if truthy(row.get("automated_use"))]
    if not rows:
        raise ValueError("registry has no automated-use rows")
    if {row["paper_japan_member_id"] for row in rows} != {"JPN_38"}:
        raise ValueError("v1 recovery contract is restricted to JPN_38")

    azami = load_azami_measurement(args.azami_measure_script)
    out_rows = []
    usable_lightness = []
    usable_chroma = []

    for row in rows:
        image_path = args.image_dir / f"{row['source_id']}.jpg"
        if not image_path.exists():
            raise FileNotFoundError(image_path)
        image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        if image is None:
            raise ValueError(f"unreadable downloaded image: {image_path}")
        result = azami.colour_measurement(image)
        state = str(result.get("state", ""))
        confidence = float(result.get("confidence") or 0.0)
        lightness = result.get("median_lab_lightness")
        chroma = result.get("median_lab_chroma")
        lightness = float(lightness) if lightness is not None and math.isfinite(float(lightness)) else None
        chroma = float(chroma) if chroma is not None and math.isfinite(float(chroma)) else None
        usable = (
            state != getattr(azami, "NON_SCOREABLE", "unassessable")
            and confidence >= args.colour_confidence_floor
            and lightness is not None
        )
        if usable:
            usable_lightness.append(lightness)
            if chroma is not None:
                usable_chroma.append(chroma)
        out_rows.append({
            "paper_japan_member_id": row["paper_japan_member_id"],
            "taxon_name": row["taxon_name"],
            "source_id": row["source_id"],
            "location": row["location"],
            "observation_date": row["observation_date"],
            "source_page_url": row["source_page_url"],
            "author": row["author"],
            "license": row["license"],
            "image_sha256": sha256(image_path),
            "image_width_px": image.shape[1],
            "image_height_px": image.shape[0],
            "measurement_state": state,
            "measurement_confidence": confidence,
            "median_lab_lightness": lightness,
            "median_lab_chroma": chroma,
            "floral_pixel_fraction": result.get("floral_pixel_fraction"),
            "mask_quality": result.get("mask_quality"),
            "usable_at_confidence_floor": usable,
            "measurement_role": row["measurement_role"],
        })

    args.per_image_output.parent.mkdir(parents=True, exist_ok=True)
    with args.per_image_output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(out_rows[0]))
        writer.writeheader()
        writer.writerows(out_rows)

    summary = {
        "contract_version": "japan38_jpn38_public_colour_recovery_v1",
        "paper_japan_member_id": "JPN_38",
        "taxon_name": "Cirsium pendulum",
        "registered_automated_sources": len(rows),
        "downloaded_images_measured": len(out_rows),
        "usable_images_at_confidence_floor": len(usable_lightness),
        "colour_confidence_floor": args.colour_confidence_floor,
        "usable_lightness_median": statistics.median(usable_lightness) if usable_lightness else None,
        "usable_lightness_mad": median_abs_deviation(usable_lightness),
        "usable_chroma_median": statistics.median(usable_chroma) if usable_chroma else None,
        "independent_population_replicates": 1,
        "population_replicate_note": "The v1 licensed sources are two images from the same Fukushima/Aizu locality, date and photographer; do not count them as two population replicates.",
        "promotion_gate": {
            "japan_local_colour_bridge_ready_from_this_recovery": False,
            "reason": "Screening images are not detector-cropped observations from the original Azami cohort and currently represent only one independent Japanese locality."
        },
        "claim_boundary": "Derived screening measurements only. Raw external images are not committed. A usable automated measurement does not by itself establish a population-matched Japan38 phenotype or satisfy the >=5 Japan-local concept history gate."
    }
    args.summary_output.write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
