from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "data/evidence/interaction_gate_hypothesis_evidence_v1.csv"
REGISTRY = ROOT / "data/evidence/interaction_gate_hypothesis_registry_v1.csv"
OUT = ROOT / "data/evidence/interaction_gate_hypothesis_summary_v1.json"


def load_csv(path: Path):
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def classify(rule: str, counts: dict[str, int]) -> str:
    ds = counts["direct_support"]
    dc = counts["direct_contradict"]
    us = counts["unique_support_groups"]
    uc = counts["unique_contradict_groups"]

    if rule == "weaken_if_direct_contradict_ge_2":
        return "weakened" if dc >= 2 and ds == 0 else "live"
    if rule == "working_if_direct_support_ge_3_no_direct_contradict":
        return "working_support" if ds >= 3 and dc == 0 else "live"
    if rule == "candidate_if_support_ge_3_cross_estimand":
        return "candidate_supported_not_identified" if us >= 3 and uc == 0 else "live"
    if rule == "candidate_if_support_ge_3_but_focal_manipulation_missing":
        return "mechanistic_candidate" if us >= 3 and uc == 0 else "live"
    if rule == "unresolved_if_support_and_contradict":
        return "unresolved" if us >= 1 and uc >= 1 else "live"
    raise ValueError(f"Unknown decision rule: {rule}")


def main() -> None:
    evidence = load_csv(EVIDENCE)
    registry = {row["hypothesis_id"]: row for row in load_csv(REGISTRY)}

    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in evidence:
        grouped[row["hypothesis_id"]].append(row)

    results = []
    for hypothesis_id, meta in registry.items():
        rows = grouped[hypothesis_id]
        support_groups = {r["independence_group"] for r in rows if r["verdict"] == "support"}
        contradict_groups = {r["independence_group"] for r in rows if r["verdict"] == "contradict"}
        ambiguous_groups = {r["independence_group"] for r in rows if r["verdict"] == "ambiguous"}
        direct_support_groups = {
            r["independence_group"]
            for r in rows
            if r["verdict"] == "support" and r["directness"] == "direct"
        }
        direct_contradict_groups = {
            r["independence_group"]
            for r in rows
            if r["verdict"] == "contradict" and r["directness"] == "direct"
        }
        counts = {
            "unique_support_groups": len(support_groups),
            "unique_contradict_groups": len(contradict_groups),
            "unique_ambiguous_groups": len(ambiguous_groups),
            "direct_support": len(direct_support_groups),
            "direct_contradict": len(direct_contradict_groups),
        }
        observed_status = classify(meta["decision_rule"], counts)
        if observed_status != meta["expected_status"]:
            raise RuntimeError(
                f"{hypothesis_id}: expected {meta['expected_status']} but audit gives {observed_status}; {counts}"
            )
        results.append(
            {
                "hypothesis_id": hypothesis_id,
                "hypothesis_name": meta["hypothesis_name"],
                "status": observed_status,
                **counts,
                "core_claim": meta["core_claim"],
                "decisive_missing_test": meta["decisive_missing_test"],
            }
        )

    summary = {
        "version": "v1",
        "hypothesis_count": len(results),
        "status_counts": dict(sorted((status, sum(r["status"] == status for r in results)) for status in {r["status"] for r in results})),
        "hypotheses": results,
        "interpretation": {
            "weakened": "A simple broad-gradient direct-scaling model is contradicted by several independent Cirsium tests and by the structural screen.",
            "working_support": "Demographic gating and reproductive-assurance buffering have repeated direct Cirsium support and are ready to become explicit focal-system predictions.",
            "new_candidates": "Conditional antagonist priority and interaction partitioning are generated by the combined meta-syntheses but are not yet identified causal conclusions.",
            "central_unresolved": "Multi-stage modularity remains unresolved because both module-specific and common-lability full models can reproduce important targets.",
        },
        "claim_boundary": "This is a preregistered-style falsification audit over heterogeneous existing evidence, not a meta-analytic effect-size model, Bayes factor, posterior probability, or vote-counting proof.",
    }
    OUT.write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
